server:
  port: 8081
  
eureka:     #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:orderdb
    username: sa
    password: 
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  application:
    name: order-persistence-service
  h2:
    console:
      enabled: true
      path: /ui-h2